---
title: Python-bytes - Receptverpesters
hero_image: images/banner.png
description: Maak en saboteer stiekem een recept met behulp van Python-opmaakfuncties en tekenreeksmethoden.
meta_title: Python-programmeerprojecten voor kinderen en tieners | Receptverpesters
meta_description: Leer Python met de Raspberry Pi Foundation. Maak en verpest stiekem een recept met behulp van print(), f-strings, emoji en .replace().
version: 1
listed: true
copyedit: false
last_tested: "2025-04-04"
steps:
  - title: step_1
  - title: step_2
    completion:
      - engaged
  - title: step_3
  - title: step_4
  - title: step_5
  - title: step_6
    completion:
      - internal
      - external
